version: "3.8"
services:
  mysql:
    container_name: mysql_yoga_db
    restart: on-failure
    image: mysql:5.7
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - yoga-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${MYSQL_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
volumes:
  yoga-mysql-data: